import "./globals.css";
import Navbar from "./profile/slices/navBar/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="app"></div>
        {children}
      </body>
    </html>
  );
}
